### ISSUE TITLE
It is better to use another font rather than Comic Sans, and make the fonts bigger!

### ISSUE THREAD

**Issue by rcswex** [Rainbow-Dreamer/Ideal-Piano#1]
最好使用其他字体而不是Comic Sans（显不正式），并使字体更大（更明显）。

**Comment by Rainbow-Dreamer** [comment]
我觉得Comic Sans挺可爱的2333，算是我最喜欢的英文字体了，而且字体类型和字体大小都是可以到config.py里自由修改的，我这个字体只是默认的设置，所以是可以设置自己想要的字体和大小的。config.py里对应的参数是：字体类型——fonts，字体大小——fonts_size，字体颜色——message_color，还有很多其他的软件参数可以修改，基本上你看到的所有东西都可以在config.py里面修改，保存之后打开exe就可以看到改变了。
