### ISSUE TITLE
Ref.: Chordie App and more

### ISSUE THREAD

**Issue by rcswex** [Rainbow-Dreamer/Ideal-Piano#2]
很棒，相当于 Chordie App 的免费开源版：https://zhuanlan.zhihu.com/p/165669547 ，可以完善功能向那个方向做。另，我们的项目“无限和声生成器”：https://github.com/Chen-and-Sim/SmartChordGen 兴许你会感兴趣，欢迎互关GitHub！

**Comment by Rainbow-Dreamer** [comment]
我这个跟Chordie要完成的目的确实是几乎一样的，我当时开坑写到一半之后看油管才发现有Chordie这个跟自己的项目很接近的软件2333，不知道Chordie使用的判断和弦的算法是怎么样的，我觉得还是挺有可能是单纯查表来实现的，不过也很有可能和我这个一样是通过很复杂的乐理逻辑算法来分析出来的。你这个项目我会去关注的，看起来挺有意思的(｀・ω・´)互关了
