### ISSUE TITLE
有其他系统的吗？

### ISSUE THREAD

**Issue by zkbqhuang** [Rainbow-Dreamer/Ideal-Piano#3]
比如：mac 和 linux(ubuntu)

**Comment by Rainbow-Dreamer** [comment]
在mac和linux上可以先安装python (>=3.6)，32位的，然后pip install pygame pyglet==1.5.11，然后把packages文件夹里的Ideal Piano start program.pyw复制粘贴到主文件夹里，点击打开就可以使用了。

**Comment by Rainbow-Dreamer** [comment]
可以到releases下载mac和linux版本
