### ISSUE TITLE
Considering integration with a monome grid

### ISSUE THREAD

**Issue by circark** [Rainbow-Dreamer/Ideal-Piano#4]
Hello

great project! 

I’m a beginner using python (and the piano) but I have an idea to integrate some of your code in my project:

i have a monome grid 256, a 16x16 LED and buttons grid :

_grid connects through USB to personal computers, modular synths, and sound computers like [norns](https://monome.org/docs/norns). It is a highly flexible interface for applications within each of these environments. grid communicates with applications to do a wide range of things: control MIDI devices, sequence modular synthesizers, cut samples, provide an isometric keyboard to software synths, change faders, visualize streams of data, etc. This core flexibility makes it hard to point to one use case and say “it does this.”_

As monome grid is also open source, I wanted to find a way to display the played chord on the 16x16 grid while playing the piano.  

The next step for me is to find in your code where the detected chord is outputted and find a way to convert the information and display it on a 16x16 grid. I will look myself in your code but maybe if you have time and or the will to help me a bit, would be lovely. 

Greetings
alrick

**Comment by Rainbow-Dreamer** [comment]
Hi, the deteced chord string is the return value `current_info` of the method `_detect_chord` of class `piano_engine` in the file `packages/Ideal Piano.pyw`. Thanks for liking this project.

**Comment by Rainbow-Dreamer** [comment]
Hi, the detected chord string is the return value `current_info` of the method `_detect_chord` of class `piano_engine` in the file `packages/Ideal Piano.pyw`. Thanks for liking this project.
