### ISSUE TITLE
Adapting for Music AI

### ISSUE THREAD

**Issue by asigalov61** [Rainbow-Dreamer/Ideal-Piano#6]
Hey @Rainbow-Dreamer 

First of all, I wanted to thank you very much for musicpy and this project. They are fantastic and I really like them.

I was wondering if you would be interested in adapting Ideal Piano for Music AI? Either as a web front-end or stand-alone app with an AI model?

Here is my Piano Music AI implementation:
https://github.com/asigalov61/GIGA-Piano

It would be really cool to integrate my models into your project for music composition (for example) so please let me know if you would be interested in something like that.

Thank you.

Most sincerely,

Alex

**Comment by Rainbow-Dreamer** [comment]
Hi, thanks for liking this project. I think develop a special version of Ideal Piano that integrate your music AI models for music composition based on input MIDI files would be pretty interesting, but I currently have kinda heavy daily jobs which leaves not much free time for me to actually try it. I spend most of my spare time improving my music programming language project musicpy. You are very welcome to fork this project and integrate your piano music AI models into this project whenever you want, and if you have any issues with this project, please let me know.

**Comment by asigalov61** [comment]
@Rainbow-Dreamer Ok. Thank you for your response :)

I will see what can be done with musicpy and I will see if I can create an AI implementation with it.

Thanks.
