### ISSUE TITLE
older version download

### ISSUE THREAD

**Issue by sugizo** [Rainbow-Dreamer/Ideal-Piano#9]
reading users instructions about compatible in mac, 
but 
can't see release version in this git repo
because 
when downloaded from the web, can't run on mac 10.12

[Is there a compatible version for Linux and macOS?](https://github.com/Rainbow-Dreamer/Ideal-Piano/blob/master/User%20Manuals/English/User%20Instructions%20(Read%20me%20first!).md#is-there-a-compatible-version-for-linux-and-macos)

**question**
where is older version that can run on mac 10.12 ?

best regards

**Comment by Rainbow-Dreamer** [comment]
Thanks for the feedback, this is a typo in the manual, it is corrected now, you can click on the link at [Is there a compatible version for Linux and macOS?](https://github.com/Rainbow-Dreamer/Ideal-Piano/blob/master/User%20Manuals/English/User%20Instructions%20(Read%20me%20first!).md#is-there-a-compatible-version-for-linux-and-macos) to download the mac version.
